apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: simple-ing
spec:
  rules:
    - host: lam1905.com
      http:
        paths:
          - path: / 
            pathType: Prefix 
            backend:
              service:
                name: caddy-svc
                port:
                  number: 42000